import { useCallback, useEffect, useState } from 'react'
import { Bot, CheckCircle2, Clock3, Copy, Edit3, MessageSquare, Play, Plus, Save, Trash2, X } from 'lucide-react'
import { api } from './lib'

type Rule = { id: string; name: string; enabled: boolean; trigger: 'incoming_sms' | 'scheduled'; senderContains?: string; textContains?: string; schedule?: string; action: 'reply' | 'send_sms' | 'notify' | 'mqtt'; destination?: string; message?: string; cooldownMs: number; maxPerDay: number; lastRunAt?: string; lastMatchedSmsId?: string; dryRun?: { valid: boolean; actionReady: boolean; cooldownReady: boolean; reason: string; wouldRun: boolean } }
type Payload = { enabled: boolean; rules: Rule[]; stats: Array<{ ruleId: string; runs: number; failures: number; lastRunAt?: string }> }

const blank = (): Rule => ({ id: crypto.randomUUID(), name: 'New automation', enabled: false, trigger: 'incoming_sms', action: 'notify', cooldownMs: 300000, maxPerDay: 10 })

export function AutomationsView({ viewer, notify }: { viewer: boolean; notify: (tone: string, text: string) => void }) {
  const [data, setData] = useState<Payload | null>(null)
  const [edit, setEdit] = useState<Rule | null>(null)
  const [busy, setBusy] = useState('')
  const load = useCallback(() => api<Payload>('/api/automation').then(setData), [])
  useEffect(() => { void load(); const timer = setInterval(load, 15000); return () => clearInterval(timer) }, [load])
  async function save(rules = data?.rules || [], enabled = data?.enabled ?? true) {
    if (viewer) return
    await api('/api/automation', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ enabled, rules: rules.map((item) => { const rule = { ...item }; delete rule.dryRun; return rule }) }) })
    notify('ok', 'Automations saved'); setEdit(null); await load()
  }
  async function run(rule: Rule) {
    if (viewer || !confirm(`Run “${rule.name}” now? SMS actions may incur carrier charges.`)) return
    setBusy(rule.id)
    try { const result = await api<{ ok: boolean; reason: string }>('/api/automation/run', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ id: rule.id }) }); notify(result.ok ? 'ok' : 'warn', result.reason) } catch (error) { notify('danger', String(error)) } finally { setBusy(''); load() }
  }
  function stats(id: string) { return data?.stats.find((item) => item.ruleId === id) }
  if (!data) return <div className="empty tall-empty"><Bot className="spin" /><strong>Loading automations…</strong></div>
  return <div className="view">
    <section className="automation-hero"><div><span className="eyebrow">Guarded rule engine</span><h2>SMS Automations</h2><p>Allowlisted actions, cooldowns, daily limits and duplicate-message protection are enforced by the backend.</p></div><div className="automation-summary"><strong>{data.rules.filter((rule) => rule.enabled).length}</strong><span>active rules</span><label className="switch"><input type="checkbox" disabled={viewer} checked={data.enabled} onChange={(e) => save(data.rules, e.target.checked)} /><i /></label></div></section>
    <section className="card"><header><div><Bot size={18} /><h2>Rules</h2></div><button className="btn primary" disabled={viewer} onClick={() => setEdit(blank())}><Plus size={15} /> New rule</button></header><div className="rule-list">{data.rules.map((rule) => { const stat = stats(rule.id); return <article className={`rule-row ${rule.enabled ? 'active' : ''}`} key={rule.id}><div className="rule-icon">{rule.trigger === 'incoming_sms' ? <MessageSquare size={18} /> : <Clock3 size={18} />}</div><div className="rule-main"><div><strong>{rule.name}</strong><span className={`chip ${rule.dryRun?.wouldRun ? 'ok' : 'idle'}`}>{rule.dryRun?.reason || 'Not evaluated'}</span></div><p>When <b>{rule.trigger === 'incoming_sms' ? 'an SMS matches' : `daily at ${rule.schedule || '—'}`}</b> → {rule.action === 'reply' ? 'reply to sender' : rule.action === 'send_sms' ? `send to ${rule.destination || '—'}` : rule.action === 'notify' ? 'send notification' : 'publish MQTT'}</p><small>{stat?.runs || 0} runs · {stat?.failures || 0} failures · cooldown {Math.round(rule.cooldownMs / 60000)} min · max {rule.maxPerDay}/day</small></div><label className="switch"><input type="checkbox" checked={rule.enabled} disabled={viewer} onChange={(e) => save(data.rules.map((item) => item.id === rule.id ? { ...item, enabled: e.target.checked } : item))} /><i /></label><button className="icon-btn" disabled={viewer || busy === rule.id} onClick={() => run(rule)} title="Run now"><Play size={16} /></button><button className="icon-btn" disabled={viewer} onClick={() => setEdit({ ...rule })}><Edit3 size={16} /></button></article>})}{data.rules.length === 0 && <div className="empty tall-empty"><Bot size={30} /><strong>No automations yet</strong><span>Create an incoming-message or scheduled rule.</span></div>}</div></section>
    <section className="safety-note"><CheckCircle2 size={18} /><div><strong>Safety defaults</strong><span>No arbitrary shell commands. Unknown SMS send outcomes are not retried. Each incoming SMS ID is processed at most once per rule.</span></div></section>
    {edit && <RuleModal rule={edit} onChange={setEdit} onClose={() => setEdit(null)} onSave={(rule) => save([...data.rules.filter((item) => item.id !== rule.id), rule])} onClone={(rule) => setEdit({ ...rule, id: crypto.randomUUID(), name: `${rule.name} copy`, enabled: false })} onDelete={(rule) => { if (confirm(`Delete “${rule.name}”?`)) save(data.rules.filter((item) => item.id !== rule.id)) }} />}
  </div>
}

function RuleModal({ rule, onChange, onClose, onSave, onClone, onDelete }: { rule: Rule; onChange: (rule: Rule) => void; onClose: () => void; onSave: (rule: Rule) => void; onClone: (rule: Rule) => void; onDelete: (rule: Rule) => void }) {
  const set = (next: Partial<Rule>) => onChange({ ...rule, ...next })
  return <div className="modal-backdrop" onClick={onClose}><section className="modal rule-modal" onClick={(e) => e.stopPropagation()}><header><div><span className="eyebrow">When → Then</span><h2>{rule.name}</h2></div><button className="icon-btn" onClick={onClose}><X size={17} /></button></header><div className="form-grid"><label className="wide">Name<input className="input" value={rule.name} onChange={(e) => set({ name: e.target.value })} /></label><label>Trigger<select className="input" value={rule.trigger} onChange={(e) => set({ trigger: e.target.value as Rule['trigger'] })}><option value="incoming_sms">Incoming SMS</option><option value="scheduled">Daily schedule</option></select></label>{rule.trigger === 'scheduled' ? <label>Time<input className="input" type="time" value={rule.schedule || '08:00'} onChange={(e) => set({ schedule: e.target.value })} /></label> : <><label>Sender contains<input className="input" value={rule.senderContains || ''} onChange={(e) => set({ senderContains: e.target.value })} placeholder="Optional" /></label><label className="wide">Message contains<input className="input" value={rule.textContains || ''} onChange={(e) => set({ textContains: e.target.value })} placeholder="Keyword or phrase" /></label></>}<label>Action<select className="input" value={rule.action} onChange={(e) => set({ action: e.target.value as Rule['action'] })}><option value="reply">Reply to sender</option><option value="send_sms">Send SMS</option><option value="notify">External notification</option><option value="mqtt">MQTT event</option></select></label>{rule.action === 'send_sms' && <label>Destination<input className="input" value={rule.destination || ''} onChange={(e) => set({ destination: e.target.value })} placeholder="+385…" /></label>}{['reply', 'send_sms'].includes(rule.action) && <label className="wide">Message<textarea className="input" rows={4} maxLength={480} value={rule.message || ''} onChange={(e) => set({ message: e.target.value })} /></label>}<label>Cooldown (minutes)<input className="input" type="number" min="0" value={Math.round(rule.cooldownMs / 60000)} onChange={(e) => set({ cooldownMs: Number(e.target.value) * 60000 })} /></label><label>Maximum per day<input className="input" type="number" min="1" max="1000" value={rule.maxPerDay} onChange={(e) => set({ maxPerDay: Number(e.target.value) })} /></label></div><div className="button-row between"><div><button className="btn danger-btn" onClick={() => onDelete(rule)}><Trash2 size={15} /> Delete</button><button className="btn" onClick={() => onClone(rule)}><Copy size={15} /> Clone</button></div><div><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={!rule.name} onClick={() => onSave(rule)}><Save size={15} /> Save rule</button></div></div></section></div>
}
