import { useEffect, useState, type ReactNode } from 'react'
import { Bell, Database, Download, KeyRound, LockKeyhole, Network, RadioTower, Save, Server, ShieldCheck, TestTube2 } from 'lucide-react'
import { api, formatBytes } from './lib'

type SettingsData = any
type Category = 'connection' | 'access' | 'notifications' | 'mqtt' | 'storage' | 'about'

export function SettingsView({ viewer, notify, onSaved }: { viewer: boolean; notify: (tone: string, text: string) => void; onSaved: () => Promise<void> }) {
  const [data, setData] = useState<SettingsData>(null)
  const [category, setCategory] = useState<Category>('connection')
  const [busy, setBusy] = useState(false)
  const [health, setHealth] = useState<any>(null)
  const [version, setVersion] = useState<any>(null)
  useEffect(() => { void Promise.all([api('/api/settings').then(setData), api('/api/admin/health').then(setHealth), api('/api/version').then(setVersion)]) }, [])
  function update(path: string, value: unknown) {
    setData((current: any) => { const next = structuredClone(current); const parts = path.split('.'); let cursor = next; for (const part of parts.slice(0, -1)) cursor = cursor[part]; cursor[parts.at(-1)!] = value; return next })
  }
  async function save() {
    if (viewer) return
    setBusy(true)
    try { setData(await api('/api/settings', { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify(data) })); notify('ok', 'Settings saved'); await onSaved() } catch (error) { notify('danger', error instanceof Error ? error.message : String(error)) } finally { setBusy(false) }
  }
  async function test(path: string, success: string) {
    setBusy(true)
    try { const result = await api<any>(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); notify(result.ok === false ? 'warn' : 'ok', result.message || success) } catch (error) { notify('danger', error instanceof Error ? error.message : String(error)) } finally { setBusy(false) }
  }
  if (!data) return <div className="empty tall-empty"><Server className="spin" /><strong>Loading settings…</strong></div>
  const categories: Array<{ id: Category; label: string; icon: ReactNode }> = [{ id: 'connection', label: 'Connection', icon: <Network size={16} /> }, { id: 'access', label: 'Access', icon: <LockKeyhole size={16} /> }, { id: 'notifications', label: 'Notifications', icon: <Bell size={16} /> }, { id: 'mqtt', label: 'MQTT & HA', icon: <RadioTower size={16} /> }, { id: 'storage', label: 'Storage', icon: <Database size={16} /> }, { id: 'about', label: 'About', icon: <ShieldCheck size={16} /> }]
  return <div className="view settings-view"><div className="settings-tabs">{categories.map((item) => <button key={item.id} className={category === item.id ? 'active' : ''} onClick={() => setCategory(item.id)}>{item.icon}{item.label}</button>)}</div>
    {category === 'connection' && <div className="grid two"><Panel title="UCG jump host" icon={<Server size={18} />} note="The app opens an SSH tunnel through this UniFi gateway."><div className="form-grid"><Field label="Host" value={data.connection.gateway.host} onChange={(v) => update('connection.gateway.host', v)} /><Field label="Port" type="number" value={data.connection.gateway.port} onChange={(v) => update('connection.gateway.port', Number(v))} /><Field label="Username" value={data.connection.gateway.user} onChange={(v) => update('connection.gateway.user', v)} /><Field label={`Password ${data.connection.gateway.passwordSet ? '(configured)' : ''}`} type="password" value={data.connection.gateway.password || ''} onChange={(v) => update('connection.gateway.password', v)} placeholder="Leave blank to keep current" /><Field label="Private key path" value={data.connection.gateway.privateKeyPath || ''} onChange={(v) => update('connection.gateway.privateKeyPath', v)} placeholder="Optional; preferred for production" /><Field label="SHA256 host fingerprint" value={data.connection.gateway.hostFingerprint || ''} onChange={(v) => update('connection.gateway.hostFingerprint', v)} placeholder="Optional; recommended for production" /></div></Panel><Panel title="U5G device" icon={<RadioTower size={18} />} note="UniFi mode reads adopted device credentials from the UCG and keeps them in memory only."><div className="form-grid"><Field label="Host" value={data.connection.modem.host} onChange={(v) => update('connection.modem.host', v)} /><Field label="Port" type="number" value={data.connection.modem.port} onChange={(v) => update('connection.modem.port', Number(v))} /><label>Authentication<select className="input" value={data.connection.modem.authMode} onChange={(e) => update('connection.modem.authMode', e.target.value)}><option value="unifi">UniFi managed credentials</option><option value="manual">Manual SSH credentials</option></select></label>{data.connection.modem.authMode === 'manual' && <><Field label="Username" value={data.connection.modem.user || ''} onChange={(v) => update('connection.modem.user', v)} /><Field label={`Password ${data.connection.modem.passwordSet ? '(configured)' : ''}`} type="password" value={data.connection.modem.password || ''} onChange={(v) => update('connection.modem.password', v)} /></>}<Field label="SHA256 host fingerprint" value={data.connection.modem.hostFingerprint || ''} onChange={(v) => update('connection.modem.hostFingerprint', v)} /></div><button className="btn" disabled={busy || viewer} onClick={() => test('/api/connection/test', 'SSH jump connected')}><TestTube2 size={15} /> Test connection</button></Panel></div>}
    {category === 'access' && <div className="grid two"><Panel title="Web access" icon={<LockKeyhole size={18} />} note="Sessions use HttpOnly SameSite cookies and login rate limiting."><Toggle label="Require login" checked={data.auth.enabled} onChange={(v) => update('auth.enabled', v)} /><Toggle label="Enable read-only viewer" checked={data.auth.viewerEnabled} onChange={(v) => update('auth.viewerEnabled', v)} /><Field label="New admin password" type="password" value={data.auth.adminPassword || ''} onChange={(v) => update('auth.adminPassword', v)} placeholder="Leave blank to keep current" />{data.auth.viewerEnabled && <Field label="New viewer password" type="password" value={data.auth.viewerPassword || ''} onChange={(v) => update('auth.viewerPassword', v)} />}</Panel><Panel title="Server" icon={<Server size={18} />} note="Host or port changes require a service restart."><Field label="Listen host" value={data.server.host} onChange={(v) => update('server.host', v)} /><Field label="Port" type="number" value={data.server.port} onChange={(v) => update('server.port', Number(v))} /><Field label="Polling interval (seconds)" type="number" value={data.server.pollIntervalMs / 1000} onChange={(v) => update('server.pollIntervalMs', Number(v) * 1000)} /></Panel></div>}
    {category === 'notifications' && <div className="grid two"><Panel title="Notification policy" icon={<Bell size={18} />}><Toggle label="Enable notifications" checked={data.notifications.enabled} onChange={(v) => update('notifications.enabled', v)} /><Toggle label="Incoming SMS" checked={data.notifications.incomingSms} onChange={(v) => update('notifications.incomingSms', v)} /><Toggle label="Connection lost" checked={data.notifications.connectionLost} onChange={(v) => update('notifications.connectionLost', v)} /><button className="btn" disabled={busy || viewer} onClick={() => test('/api/notifications/test', 'Test notification sent')}><TestTube2 size={15} /> Send test</button></Panel><Panel title="ntfy" icon={<Bell size={18} />}><Toggle label="Enable ntfy" checked={data.notifications.ntfy.enabled} onChange={(v) => update('notifications.ntfy.enabled', v)} /><Field label="Server URL" value={data.notifications.ntfy.url} onChange={(v) => update('notifications.ntfy.url', v)} /><Field label="Topic" value={data.notifications.ntfy.topic} onChange={(v) => update('notifications.ntfy.topic', v)} /></Panel><Panel title="Telegram" icon={<MessageIcon />}><Toggle label="Enable Telegram" checked={data.notifications.telegram.enabled} onChange={(v) => update('notifications.telegram.enabled', v)} /><Field label={`Bot token ${data.notifications.telegram.tokenSet ? '(configured)' : ''}`} type="password" value={data.notifications.telegram.botToken || ''} onChange={(v) => update('notifications.telegram.botToken', v)} /><Field label="Chat ID" value={data.notifications.telegram.chatId} onChange={(v) => update('notifications.telegram.chatId', v)} /></Panel><Panel title="E-mail" icon={<Bell size={18} />}><Toggle label="Enable e-mail" checked={data.notifications.email.enabled} onChange={(v) => update('notifications.email.enabled', v)} /><div className="form-grid"><Field label="SMTP host" value={data.notifications.email.host} onChange={(v) => update('notifications.email.host', v)} /><Field label="Port" type="number" value={data.notifications.email.port} onChange={(v) => update('notifications.email.port', Number(v))} /><Field label="Username" value={data.notifications.email.user} onChange={(v) => update('notifications.email.user', v)} /><Field label={`Password ${data.notifications.email.passwordSet ? '(configured)' : ''}`} type="password" value={data.notifications.email.password || ''} onChange={(v) => update('notifications.email.password', v)} /><Field label="From" value={data.notifications.email.from} onChange={(v) => update('notifications.email.from', v)} /><Field label="To" value={data.notifications.email.to} onChange={(v) => update('notifications.email.to', v)} /></div></Panel></div>}
    {category === 'mqtt' && <div className="grid two"><Panel title="MQTT broker" icon={<RadioTower size={18} />}><Toggle label="Enable MQTT" checked={data.mqtt.enabled} onChange={(v) => update('mqtt.enabled', v)} /><Field label="Broker URL" value={data.mqtt.url} onChange={(v) => update('mqtt.url', v)} /><Field label="Username" value={data.mqtt.username} onChange={(v) => update('mqtt.username', v)} /><Field label={`Password ${data.mqtt.passwordSet ? '(configured)' : ''}`} type="password" value={data.mqtt.password || ''} onChange={(v) => update('mqtt.password', v)} /><Field label="Base topic" value={data.mqtt.baseTopic} onChange={(v) => update('mqtt.baseTopic', v)} /></Panel><Panel title="Home Assistant" icon={<ShieldCheck size={18} />}><Toggle label="Discovery" checked={data.mqtt.homeAssistantDiscovery} onChange={(v) => update('mqtt.homeAssistantDiscovery', v)} /><Field label="Discovery prefix" value={data.mqtt.discoveryPrefix} onChange={(v) => update('mqtt.discoveryPrefix', v)} /><p className="panel-note">Creates connection, signal, carrier, band and unread-SMS entities.</p></Panel></div>}
    {category === 'storage' && <div className="grid two"><Panel title="Retention" icon={<Database size={18} />}><Field label="Metrics days" type="number" value={data.retention.metricsDays} onChange={(v) => update('retention.metricsDays', Number(v))} /><Field label="Events days" type="number" value={data.retention.eventsDays} onChange={(v) => update('retention.eventsDays', Number(v))} /><Field label="Audit days" type="number" value={data.retention.auditDays} onChange={(v) => update('retention.auditDays', Number(v))} /><Field label="Maximum metrics" type="number" value={data.retention.maxMetrics} onChange={(v) => update('retention.maxMetrics', Number(v))} /></Panel><Panel title="Database" icon={<Database size={18} />}><div className="rows"><div className="row"><span>Size</span><strong>{formatBytes(health?.database?.sizeBytes)}</strong></div>{Object.entries(health?.database?.tables || {}).map(([key, value]) => <div className="row" key={key}><span>{key}</span><strong>{String(value)}</strong></div>)}</div><div className="button-row"><a className="btn" href="/api/admin/backup"><Download size={15} /> Redacted backup</a><button className="btn" disabled={viewer} onClick={() => test('/api/admin/compact', 'Database compacted')}>Compact</button></div></Panel></div>}
    {category === 'about' && <div className="grid two"><Panel title="UniFi U5G Monitor" icon={<RadioTower size={18} />}><div className="rows"><div className="row"><span>Version</span><strong>{version?.version}</strong></div><div className="row"><span>Node</span><strong>{version?.node}</strong></div><div className="row"><span>Started</span><strong>{version?.startedAt ? new Date(version.startedAt).toLocaleString() : '—'}</strong></div><div className="row"><span>Architecture</span><strong>React · Fastify · SQLite · SSH2</strong></div></div></Panel><Panel title="Security model" icon={<KeyRound size={18} />}><ul className="feature-list"><li>UCG SSH jump with optional host-key pinning</li><li>U5G credentials can be read from UniFi and held in memory only</li><li>No browser-triggered arbitrary shell commands</li><li>Write-only secrets and redacted backups</li><li>Unknown SMS results are never retried automatically</li></ul></Panel></div>}
    <div className="settings-save"><span>{data.auth.seededDefault && 'Change the default admin password before remote access.'}</span><button className="btn primary" disabled={busy || viewer} onClick={save}><Save size={15} /> {busy ? 'Saving…' : 'Save settings'}</button></div>
  </div>
}

function Panel({ title, icon, note, children }: { title: string; icon: ReactNode; note?: string; children: ReactNode }) { return <section className="card settings-panel"><header><div>{icon}<h2>{title}</h2></div></header>{note && <p className="panel-note">{note}</p>}{children}</section> }
function Field({ label, value, onChange, type = 'text', placeholder = '' }: { label: string; value: string | number; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label>{label}<input className="input" type={type} value={value ?? ''} placeholder={placeholder} onChange={(e) => onChange(e.target.value)} /></label> }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><span className="switch"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><i /></span></label> }
function MessageIcon() { return <Bell size={18} /> }
