import { useEffect, useState, type ReactNode } from 'react'
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Activity, Antenna, ArrowDown, Cable, Cpu, Database, FileJson, Globe2, HardDrive, MemoryStick, Network, RadioTower, RefreshCw, ScrollText, Server, ShieldCheck, Signal, Smartphone, Terminal, Wifi } from 'lucide-react'
import { api, formatBytes, formatRate, type EventRow, type Status, type TabId, type TrendPoint } from './lib'

type Common = { status: Status | null; history: TrendPoint[]; events: EventRow[]; viewer: boolean; onRefresh: () => Promise<void>; notify: (tone: string, text: string) => void }
type Diagnostics = { generatedAt: string; version: string; uptime: string; network: string; rawStatus: unknown; logs: Record<'modem' | 'network' | 'sms' | 'system', string>; fingerprints: Record<string, string> }

function Card({ title, icon, action, children, className = '' }: { title: string; icon?: ReactNode; action?: ReactNode; children: ReactNode; className?: string }) {
  return <section className={`card ${className}`}><header><div>{icon}<h2>{title}</h2></div>{action}</header>{children}</section>
}

function Metric({ label, value, note, tone = '' }: { label: string; value: ReactNode; note?: string; tone?: string }) {
  return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>
}

function display(value: unknown): ReactNode {
  if (value == null || value === '') return '—'
  if (typeof value === 'boolean') return value ? 'Yes' : 'No'
  if (typeof value === 'object') return JSON.stringify(value)
  return String(value)
}

function Rows({ rows }: { rows: Array<[string, unknown]> }) {
  return <div className="rows">{rows.map(([key, value]) => <div className="row" key={key}><span>{key}</span><strong>{display(value)}</strong></div>)}</div>
}

function Json({ value, empty = 'No data reported by the modem.' }: { value: unknown; empty?: string }) {
  if (value == null || (Array.isArray(value) && value.length === 0) || (typeof value === 'object' && Object.keys(value as object).length === 0)) return <div className="empty">{empty}</div>
  return <pre className="json-block embedded">{JSON.stringify(value, null, 2)}</pre>
}

function field(record: Record<string, unknown> | undefined, key: string) { return record?.[key] }

function quality(value?: number, good = -90, weak = -105) {
  if (value == null) return 'idle'
  return value >= good ? 'ok' : value >= weak ? 'warn' : 'danger'
}

export function OverviewView(props: Common & { onNavigate: (tab: TabId) => void }) {
  const { status, history, events, onNavigate } = props
  const radio = status?.radio
  const sim = status?.sim
  return <div className="view">
    <section className="hero-panel"><div><span className="eyebrow">{radio?.operator || 'Cellular modem'}</span><h2>{status?.device?.modelDisplay || 'UniFi U5G'}</h2><p>{radio?.rat || '—'} · {radio?.band || 'no band'} · PCI {radio?.pci ?? '—'} · Cell {radio?.cellId ?? '—'}</p></div><div className={`signal-orb ${quality(radio?.nr?.rsrp ?? radio?.lte?.rsrp)}`}><Signal /><strong>{radio?.signalPercent ?? 0}%</strong><span>{radio?.mode || 'offline'}</span></div></section>
    <div className="metric-grid"><Metric label="Connection" value={status?.connected ? 'Online' : 'Offline'} note={`via UCG · ${status?.connection.latencyMs ?? '—'} ms`} tone={status?.connected ? 'ok' : 'danger'} /><Metric label="5G RSRP" value={radio?.nr?.rsrp != null ? `${radio.nr.rsrp} dBm` : '—'} note={`SINR ${radio?.nr?.snr ?? '—'} dB`} tone={quality(radio?.nr?.rsrp)} /><Metric label="LTE RSRP" value={radio?.lte?.rsrp != null ? `${radio.lte.rsrp} dBm` : '—'} note={`SINR ${radio?.lte?.snr ?? '—'} dB`} tone={quality(radio?.lte?.rsrp)} /><Metric label="SMS" value={status?.sms?.unread ?? 0} note={`${status?.sms?.inbox ?? 0} inbox · ${status?.sms?.outbox ?? 0} outbox`} tone={status?.sms?.failed ? 'warn' : 'ok'} /></div>
    <div className="grid two"><Card title="Signal history" icon={<Activity size={18} />} action={<button className="text-btn" onClick={() => onNavigate('signal')}>Details</button>}><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="ts" tickFormatter={(v) => new Date(v).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} minTickGap={42} /><YAxis domain={[-125, -65]} /><Tooltip labelFormatter={(v) => new Date(v).toLocaleString()} /><Line type="monotone" dataKey="nrRsrp" name="5G RSRP" stroke="#62a9ff" dot={false} strokeWidth={2} /><Line type="monotone" dataKey="lteRsrp" name="LTE RSRP" stroke="#64d8a4" dot={false} strokeWidth={2} /></LineChart></ResponsiveContainer></div></Card><Card title="SIM & carrier" icon={<Smartphone size={18} />}><Rows rows={[["Carrier", sim?.carrier || radio?.operator], ["SIM slot", sim?.slot], ["Type", sim?.esim ? 'eSIM' : 'Nano SIM'], ["State", sim?.state], ["ICCID", sim?.iccidMasked], ["IMEI", sim?.imeiMasked], ["EID", sim?.eidMasked], ["APN", sim?.apn], ["Roaming", radio?.roaming]]} /></Card></div>
    <div className="grid two"><Card title="WAN" icon={<Globe2 size={18} />}><Rows rows={[["Public IP", status?.wan?.publicIp], ["Provider", status?.wan?.isp], ["Gateway link", status?.wan?.ipv4], ["DNS", status?.wan?.dns?.join(', ')], ["MTU", status?.wan?.mtu]]} /></Card><Card title="Recent activity" icon={<RefreshCw size={18} />}><div className="event-list">{events.slice(-6).reverse().map((event) => <div className={`event ${event.level}`} key={`${event.id}-${event.ts}`}><i /><div><strong>{event.message}</strong><span>{new Date(event.ts).toLocaleString()} · {event.kind}</span></div></div>)}{events.length === 0 && <div className="empty">No events yet</div>}</div></Card></div>
  </div>
}

export function SignalView({ status, history }: Common) {
  const radio = status?.radio
  return <div className="view">
    <div className="metric-grid six"><Metric label="Mode" value={radio?.mode || '—'} /><Metric label="Registration" value={radio?.registrationState || '—'} /><Metric label="Band" value={radio?.band || '—'} /><Metric label="Cell / PCI" value={`${radio?.cellId ?? '—'} / ${radio?.pci ?? '—'}`} /><Metric label="RX / TX channel" value={`${radio?.rxChannel ?? '—'} / ${radio?.txChannel ?? '—'}`} /><Metric label="Signal" value={`${radio?.signalPercent ?? 0}%`} /></div>
    <Card title="LTE and 5G radio history" icon={<Antenna size={18} />} action={<a className="text-btn" href="/api/export/metrics.csv?minutes=1440" title="Export CSV">Export CSV</a>}><div className="chart tall"><ResponsiveContainer width="100%" height="100%"><LineChart data={history}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="ts" tickFormatter={(v) => new Date(v).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} /><YAxis yAxisId="dbm" domain={[-130, -60]} /><YAxis yAxisId="db" orientation="right" domain={[-20, 40]} /><Tooltip labelFormatter={(v) => new Date(v).toLocaleString()} /><Line yAxisId="dbm" dataKey="nrRsrp" name="5G RSRP" stroke="#62a9ff" dot={false} strokeWidth={2} /><Line yAxisId="dbm" dataKey="lteRsrp" name="LTE RSRP" stroke="#64d8a4" dot={false} strokeWidth={2} /><Line yAxisId="db" dataKey="nrSnr" name="5G SINR" stroke="#d49bff" dot={false} /><Line yAxisId="db" dataKey="lteSnr" name="LTE SINR" stroke="#ffc56a" dot={false} /></LineChart></ResponsiveContainer></div></Card>
    <div className="grid two"><Card title="Current measurements" icon={<Signal size={18} />}><div className="metric-grid"><Metric label="5G RSRP" value={`${radio?.nr?.rsrp ?? '—'} dBm`} tone={quality(radio?.nr?.rsrp)} /><Metric label="5G RSRQ" value={`${radio?.nr?.rsrq ?? '—'} dB`} /><Metric label="5G SINR" value={`${radio?.nr?.snr ?? '—'} dB`} /><Metric label="LTE RSRP" value={`${radio?.lte?.rsrp ?? '—'} dBm`} tone={quality(radio?.lte?.rsrp)} /><Metric label="LTE RSRQ" value={`${radio?.lte?.rsrq ?? '—'} dB`} /><Metric label="LTE RSSI / SINR" value={`${radio?.lte?.rssi ?? '—'} / ${radio?.lte?.snr ?? '—'} dB`} /></div></Card><Card title="Registration & mode" icon={<RadioTower size={18} />}><Rows rows={[["RAT", radio?.rat], ["Active mode", radio?.mode], ["5G SA mode", radio?.saMode], ["Current SIM slot", radio?.currentSlot], ["MCC / MNC", `${radio?.mcc ?? '—'} / ${radio?.mnc ?? '—'}`], ["Home PLMN serving", radio?.homePlmnServing], ["Home PLMN denied", radio?.homePlmnDenied], ["Coverage", radio?.coverage], ["Roaming", radio?.roaming]]} /></Card></div>
    <Card title="Carrier aggregation — every active carrier" icon={<Network size={18} />}><div className="carrier-list">{radio?.lteCa?.map((carrier, index) => <div className="carrier" key={`lte-${index}`}><span>{carrier.primary ? 'LTE primary' : `LTE carrier ${index + 1}`}</span><strong>B{carrier.band} · DL {carrier.dl_bw_mhz ?? '—'} / UL {carrier.ul_bw_mhz ?? '—'} MHz</strong><small>DL EARFCN {carrier.dl_earfcn ?? '—'} · UL EARFCN {carrier.ul_earfcn ?? '—'}</small></div>)}{radio?.nrCa?.map((carrier, index) => <div className="carrier nr" key={`nr-${index}`}><span>{carrier.primary ? '5G primary' : `5G carrier ${index + 1}`}</span><strong>n{carrier.band} · DL {carrier.dl_bw_mhz ?? '—'} / UL {carrier.ul_bw_mhz ?? '—'} MHz</strong><small>DL ARFCN {carrier.dl_arfcn ?? '—'} · UL ARFCN {carrier.ul_arfcn ?? '—'}</small></div>)}{!radio?.lteCa?.length && !radio?.nrCa?.length && <div className="empty">No carrier data</div>}</div></Card>
    <div className="grid two"><Card title="Supported bands" icon={<Antenna size={18} />}><Rows rows={[["LTE bands", radio?.supportedLteBands?.join(', ')], ["5G NR bands", radio?.supportedNrBands?.join(', ')], ["RAT capabilities", radio?.ratCapabilities?.join(', ')]]} /></Card><Card title="Network scan & operators" icon={<Globe2 size={18} />}><Json value={status?.sim?.networkScan} /></Card></div>
  </div>
}

export function DataView({ status, history }: Common) {
  const slots = status?.sim?.slots ?? []
  return <div className="view">
    <div className="metric-grid"><Metric label="Downloaded" value={formatBytes(status?.sim?.rxBytes)} /><Metric label="Uploaded" value={formatBytes(status?.sim?.txBytes)} /><Metric label="Peak download" value={formatRate(status?.radio?.maxDownBps)} /><Metric label="Peak upload" value={formatRate(status?.radio?.maxUpBps)} /></div>
    <Card title="Session data counters" icon={<ArrowDown size={18} />}><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={history}><defs><linearGradient id="rx" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#62a9ff" stopOpacity={.4}/><stop offset="95%" stopColor="#62a9ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="ts" tickFormatter={(v) => new Date(v).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} /><YAxis tickFormatter={(v) => formatBytes(v)} /><Tooltip formatter={(v) => formatBytes(Number(v))} labelFormatter={(v) => new Date(v).toLocaleString()} /><Area type="monotone" dataKey="rxBytes" name="RX" stroke="#62a9ff" fill="url(#rx)" /><Area type="monotone" dataKey="txBytes" name="TX" stroke="#64d8a4" fillOpacity={0} /></AreaChart></ResponsiveContainer></div></Card>
    <div className="grid two"><Card title="Carrier WAN" icon={<Globe2 size={18} />}><Rows rows={[["Public IP", status?.wan?.publicIp], ["ISP", status?.wan?.isp], ["ASN", status?.wan?.asn ? `AS${status.wan.asn}` : undefined], ["Location", [status?.wan?.city, status?.wan?.country].filter(Boolean).join(', ')], ["IPv4", status?.wan?.ipv4], ["Gateway", status?.wan?.gateway], ["Netmask", status?.wan?.netmask], ["DNS", status?.wan?.dns?.join(', ')], ["MTU", status?.wan?.mtu]]} /></Card><Card title="IPv6 & connection state" icon={<Network size={18} />}><Rows rows={[["Device IPv6", status?.device?.ipv6?.join(', ')], ["Connection state", field(status?.wan?.connectionInfo, 'inet_state')], ["IP type", field(status?.wan?.connectionInfo, 'ip_type')], ["Timestamp", field(status?.wan?.connectionInfo, 'timestamp')]]} /><Json value={status?.wan?.ipv6} /></Card></div>
    <Card title="Ethernet detailed counters" icon={<Cable size={18} />}><div className="metric-grid"><Metric label="Link" value={status?.ethernet?.up ? 'Up' : 'Down'} note={`${status?.ethernet?.speedMbps ?? '—'} Mbit/s · ${status?.ethernet?.fullDuplex ? 'full' : 'half'} duplex`} /><Metric label="RX" value={formatBytes(status?.ethernet?.rxBytes)} note={`${status?.ethernet?.rxPackets ?? '—'} packets`} /><Metric label="TX" value={formatBytes(status?.ethernet?.txBytes)} note={`${status?.ethernet?.txPackets ?? '—'} packets`} /><Metric label="Errors / dropped" value={`${status?.ethernet?.rxErrors ?? 0}/${status?.ethernet?.txErrors ?? 0}`} note={`RX drop ${status?.ethernet?.rxDropped ?? 0} · TX drop ${status?.ethernet?.txDropped ?? 0} · multicast ${status?.ethernet?.rxMulticast ?? 0}`} /></div></Card>
    <div className="grid two">{slots.map((slot, index) => <Card key={index} title={`SIM slot ${display(field(slot, 'slot'))}${field(slot, 'active') ? ' · active' : ''}`} icon={<Smartphone size={18} />}><Rows rows={[["Present", field(slot, 'present')], ["Type", field(slot, 'esim') ? 'eSIM' : 'Nano SIM'], ["State", field(slot, 'state')], ["Carrier", field(slot, 'carrier')], ["MCC / MNC", `${display(field(slot, 'mcc'))} / ${display(field(slot, 'mnc'))}`], ["ICCID", field(slot, 'iccidMasked')], ["APN", field(slot, 'apn')], ["PDP type", field(slot, 'apnType')], ["APN auth", field(slot, 'apnAuth')], ["APN username", field(slot, 'apnUsername')], ["PIN verified", field(slot, 'pinVerified')], ["PIN / PUK tries", `${display(field(slot, 'pinTriesRemaining'))} / ${display(field(slot, 'pukTriesRemaining'))}`], ["Has data plan", field(slot, 'hasDataPlan')], ["RX / TX", `${formatBytes(Number(field(slot, 'rxBytes')))} / ${formatBytes(Number(field(slot, 'txBytes')))}`]]} /></Card>)}</div>
    <Card title="eSIM profiles" icon={<Smartphone size={18} />}><Json value={status?.sim?.esimProfiles} /></Card>
  </div>
}

export function SystemView({ status, viewer, notify }: Common) {
  const [health, setHealth] = useState<any>(null)
  useEffect(() => { void api('/api/admin/health').then(setHealth).catch(() => undefined) }, [])
  async function download() { window.open('/api/admin/diagnostics', '_blank') }
  async function compact() { try { await api('/api/admin/compact', { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); notify('ok', 'Database compacted') } catch (error) { notify('danger', String(error)) } }
  return <div className="view">
    <div className="grid two"><Card title="U5G device" icon={<Server size={18} />}><Rows rows={[["Model", status?.device?.modelDisplay], ["Firmware", status?.device?.version], ["Modem firmware", status?.device?.firmwareVersion], ["Required version", status?.device?.requiredVersion], ["Serial", status?.device?.serial], ["MAC", status?.device?.mac], ["Kernel", status?.device?.kernelVersion], ["Architecture", status?.device?.architecture], ["Uptime", status?.device?.uptimeText]]} /></Card><Card title="System resources" icon={<Cpu size={18} />}><div className="metric-grid"><Metric label="CPU" value={`${status?.device?.cpuPercent ?? '—'}%`} /><Metric label="Memory" value={`${status?.device?.memoryPercent ?? '—'}%`} note={`${formatBytes(status?.system?.memoryUsed)} / ${formatBytes(status?.system?.memoryTotal)}`} /><Metric label="Load average" value={`${status?.system?.load1 ?? '—'}`} note={`${status?.system?.load5 ?? '—'} / ${status?.system?.load15 ?? '—'} (5m/15m)`} /><Metric label="eMMC wear" value={status?.device?.emmcWearLevel ?? '—'} note={`buffer ${formatBytes(status?.system?.memoryBuffer)}`} /></div></Card></div>
    <div className="grid two"><Card title="Boot & hardware" icon={<HardDrive size={18} />}><Rows rows={[["Boot ID", status?.device?.bootId], ["Boot reason", status?.device?.bootReason], ["Dual boot", status?.device?.dualBoot], ["Ever crashed", status?.device?.everCrash], ["Board revision", status?.device?.boardRevision], ["BOM revision", status?.device?.bomRevision], ["Bootrom", status?.device?.bootromVersion], ["Manufacturer ID", status?.device?.manufacturerId], ["System ID", status?.device?.systemId], ["Reboot duration", status?.system?.rebootDuration], ["Upgrade duration", status?.system?.upgradeDuration]]} /></Card><Card title="Modem & firmware capabilities" icon={<MemoryStick size={18} />}><Json value={{ modemState: status?.system?.modemState, hardware: status?.device?.hardwareCapabilities, firmware: status?.device?.firmwareCapabilities, lastConnectionErrors: status?.system?.lastConnectionErrors }} /></Card></div>
    <div className="grid two"><Card title="Adoption & inform" icon={<Network size={18} />}><Rows rows={[["State", status?.system?.state], ["Adoption", status?.management?.adoptionState], ["Gateway", status?.management?.gatewayIp], ["Inform URL", status?.management?.informUrl], ["Inform minimum interval", status?.management?.informInterval], ["Config version", status?.management?.configVersion], ["Saved config", status?.management?.savedConfigVersion], ["Effective config", status?.management?.effectiveConfigVersion], ["Isolated", status?.management?.isolated], ["Locating", status?.management?.locating], ["Fingerprint", status?.management?.fingerprint]]} /></Card><Card title="LLDP & SSH sessions" icon={<ShieldCheck size={18} />}><h3 className="subhead">LLDP</h3><Json value={status?.management?.lldp} /><h3 className="subhead">SSH sessions</h3><Json value={status?.management?.sshSessions} /></Card></div>
    <div className="grid two"><Card title="SSH jump" icon={<ShieldCheck size={18} />}><Rows rows={[["Gateway", status?.connection.gatewayHost], ["U5G", status?.connection.modemHost], ["Mode", status?.connection.mode], ["Round trip", status?.connection.latencyMs ? `${status.connection.latencyMs} ms` : undefined], ["State", status?.connected ? 'Connected' : 'Offline']]} /></Card><Card title="Database" icon={<Database size={18} />}><Rows rows={[["Size", formatBytes(health?.database?.sizeBytes)], ["SMS", health?.database?.tables?.sms_messages], ["Metrics", health?.database?.tables?.metrics], ["Events", health?.database?.tables?.events], ["Collector", health?.pollRunning ? 'Running' : 'Idle'], ["Service uptime", health?.uptimeSeconds ? `${Math.floor(health.uptimeSeconds / 3600)}h` : undefined]]} /><div className="button-row"><button className="btn" onClick={download}>Download diagnostics</button><button className="btn" disabled={viewer} onClick={compact}>Compact</button></div></Card></div>
  </div>
}

export function DiagnosticsView({ notify }: Common) {
  const [data, setData] = useState<Diagnostics | null>(null)
  const [busy, setBusy] = useState(false)
  const [log, setLog] = useState<keyof Diagnostics['logs']>('modem')
  async function load() { setBusy(true); try { setData(await api<Diagnostics>('/api/diagnostics/live')) } catch (error) { notify('danger', error instanceof Error ? error.message : String(error)) } finally { setBusy(false) } }
  // Load once on mount only — diagnostics pulls a live mca-dump over SSH, so it must not re-run on every parent re-render (e.g. each websocket poll tick).
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [])
  return <div className="view diagnostics-view">
    <section className="safety-note"><ShieldCheck size={18} /><div><strong>Read-only and redacted</strong><span>IMEI, ICCID, EID, APN credentials, usernames, passwords, tokens and long SIM identifiers are masked before reaching the browser.</span></div><button className="btn" onClick={load} disabled={busy}><RefreshCw size={15} className={busy ? 'spin' : ''} /> Refresh</button></section>
    {!data && <div className="empty tall-empty"><Terminal className={busy ? 'spin' : ''} size={30} /><strong>Collecting live U5G diagnostics…</strong></div>}
    {data && <><div className="grid two"><Card title="Runtime & firmware" icon={<Terminal size={18} />}><pre className="terminal-block">{`${data.version}\n${data.uptime}`}</pre></Card><Card title="Network interfaces & routes" icon={<Network size={18} />}><pre className="terminal-block">{data.network}</pre></Card></div><Card title="Read-only service logs" icon={<ScrollText size={18} />} action={<div className="filter-tabs">{(['modem', 'network', 'sms', 'system'] as const).map((item) => <button key={item} className={log === item ? 'active' : ''} onClick={() => setLog(item)}>{item}</button>)}</div>}><pre className="terminal-block logs">{data.logs[log] || `No ${log} log entries.`}</pre></Card><Card title="Complete redacted mca-dump" icon={<FileJson size={18} />}><pre className="json-block raw-dump">{JSON.stringify(data.rawStatus, null, 2)}</pre></Card><Card title="Pinned SSH host keys" icon={<ShieldCheck size={18} />}><Json value={data.fingerprints} /></Card></>}
  </div>
}

export function MqttView({ viewer, notify }: Common) {
  const [state, setState] = useState<any>(null)
  const load = () => api('/api/mqtt').then(setState).catch(() => undefined)
  useEffect(() => { void load(); const timer = setInterval(load, 5000); return () => clearInterval(timer) }, [])
  async function action(path: string) { try { await api(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); notify('ok', 'MQTT action completed'); load() } catch (error) { notify('danger', String(error)) } }
  return <div className="view"><div className="metric-grid"><Metric label="MQTT" value={state?.enabled ? 'Enabled' : 'Disabled'} tone={state?.enabled ? 'ok' : 'idle'} /><Metric label="Broker" value={state?.connected ? 'Connected' : 'Offline'} tone={state?.connected ? 'ok' : 'warn'} /></div><Card title="MQTT activity" icon={<Wifi size={18} />} action={<div className="button-row"><button className="btn" disabled={viewer} onClick={() => action('/api/mqtt/publish')}>Publish state</button><button className="btn" disabled={viewer} onClick={() => action('/api/mqtt/discovery')}>HA discovery</button></div>}><div className="log-list">{state?.log?.slice().reverse().map((row: any, index: number) => <div key={`${row.ts}-${index}`}><time>{new Date(row.ts).toLocaleString()}</time><strong>{row.level}</strong><span>{row.message}</span></div>)}{!state?.log?.length && <div className="empty">MQTT has no activity. Configure it in Settings.</div>}</div></Card></div>
}
